apiVersion: v1 
kind: PersistentVolume 
metadata:
  name: mongodb-pv
  namespace: development
spec:
  storageClassName: mongo-storage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi 
    