apiVersion: v1 
kind: Service 
metadata:
  name: mongodb 
  namespace: development
spec:
  ports:
    - name: mongodb 
      port: 27017 
      nodePort: 30332
  type: NodePort
  selector:
    app: mongo-db