apiVersion: v1
kind: PersistentVolume 
metadata:
  name: mongodb-pv
spec:
  storageClassName:  mongodb-storage-class
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  local:
    path: /mnt/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: size 
              operator: In 
              values:
                - large
  
