apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:
  name: mongodb-pvc
  namespace: production
spec:
  storageClassName: gcp-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi